urls.py
from django.urls import path
from . import views
app_name = 'hospital'
urlpatterns = [
    path('', views.index, name='index'),
    path('DoctorRegistration', views.DoctorRegistration, name='doctor'),
    path('PatientRegistration', views.PatientRegistration, name='patient'),
    path('AppointmentRegistration', views.AppointmentRegistration, name='appoint'),
    path('AppointmentPost', views.AppointmentPost, name='appointpost'),
    path('AppointmentAjax', views.AppointmentAjax, name='ajaxreq'),
    path('DoctorList', views.DoctorList, name='doclist'),
    path('DoctorModal', views.DoctorModal, name='docmodal'),
    path('DoctorEdit', views.DoctorEdit, name='docedit'),
    path('DoctorDelete', views.DoctorDelete, name='docdel'),
    path('PatientList', views.PatientList, name='patlist'),
    path('PatientModal', views.PatientModal, name='patmodal'),
    path('PatientEdit', views.PatientEdit, name='patedit'),
    path('PatientDelete', views.PatientDelete, name='patdel'),
    path('AppointmentList', views.AppointmentList, name='appointlist'),
    path('AppointmentModal', views.AppointmentModal, name='appointmodal'),
    path('AppointmentEdit', views.AppointmentEdit, name='appointedit'),
    path('AppointmentDelete', views.AppointmentDelete, name='appointdel')
]

models.py
from django.db import models

class doctor(models.Model):
            emp = models.IntegerField(default=0)
            name = models.CharField(max_length=200)
            address = models.CharField(max_length=200)
            phone = models.IntegerField(default=0)
            specialize = models.CharField(max_length=200)

class patient(models.Model):
            enroll = models.IntegerField(default=0)
            name = models.CharField(max_length=200)
            address = models.CharField(max_length=200)
            phone = models.IntegerField(default=0)
            blood_group = models.CharField(max_length=200)

class visit(models.Model):
            emp = models.IntegerField(default=0)
            enroll = models.IntegerField(default=0)
            category = models.CharField(max_length=200)
            time = models.TimeField(max_length=200)
            date = models.DateField(max_length=200)

views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from hospital.models import visit, patient, doctor
from django.http import JsonResponse

def index(request):
    return render(request, 'hospital/index.html')

def DoctorRegistration(request):
    rec = doctor()
    if request.method == 'POST':
        rec.name = request.POST['name']
        rec.address = request.POST['address']
        rec.specialize = request.POST['specialize']
        rec.phone = request.POST['phone']
        rec.emp = request.POST['emp']
        rec.save()
        return redirect('hospital:doclist')
    return render(request, 'hospital/doctor/insert.html')

def PatientRegistration(request):
    rec = patient()
    if request.method == 'POST':
        rec.name = request.POST['name']
        rec.address = request.POST['address']
        rec.blood_group = request.POST['blood']
        rec.phone = request.POST['phone']
        rec.enroll = request.POST['enroll']
        rec.save()
        return redirect('hospital:patlist')
    return render(request, 'hospital/patient/insert.html')

def AppointmentRegistration(request):
    data = doctor.objects.all()
    return render(request, 'hospital/appointment/appointment.html', {'data':data})

def AppointmentPost(request):
        try:
            get_object_or_404(patient, id=request.POST['id'])
        except(Exception):
            patientrecord = patient()
            patientrecord.name = request.POST['name']
            patientrecord.address = request.POST['address']
            patientrecord.blood_group = request.POST['blood_group']
            patientrecord.phone = request.POST['phone']
            patientrecord.enroll = request.POST['enroll']
            patientrecord.save()
        finally:
            appointment = visit()
            appointment.enroll = request.POST['enroll']
            appointment.category = request.POST['category']
            appointment.time = request.POST['time']
            appointment.date = request.POST['date']
            appointment.emp = request.POST['emp']
            appointment.save()
            return redirect('hospital:appointlist')
        return render(request, 'hospital/appointment/appointment.html')

@csrf_exempt
def AppointmentAjax(request):
    data=patient.objects.get(phone=request.POST['mob'])
    resp={}
    resp['id'] = data.id
    resp['name'] = data.name
    resp['address']=data.address
    resp['phone'] = data.phone
    resp['blood_group'] = data.blood_group
    resp['enroll'] = data.enroll
    return JsonResponse(resp)

def DoctorList(request):
    rec = doctor.objects.all()
    return render(request, 'hospital/doctor/view.html', {'rec': rec})

def DoctorModal(request):
    data = doctor.objects.get(id=request.GET['modalid'])
    rec={}
    rec['id'] = data.id
    rec['name']=data.name
    rec['address']=data.address
    rec['phone'] = data.phone
    rec['specialize'] = data.specialize
    rec['emp'] = data.emp
    return JsonResponse(rec)

def DoctorEdit(request):
    data = doctor.objects.get(id=request.POST['docid'])
    if request.method == 'POST' :
     data.name = request.POST['name']
     data.address = request.POST['address']
     data.specialize = request.POST['specialize']
     data.phone = request.POST['phone']
     data.emp = request.POST['emp']
     data.save()
     return render(request, 'hospital/doctor/view.html')

def DoctorDelete(request):
    rec = doctor.objects.get(id=request.GET['deleteid'])
    rec.delete()
    return render(request, 'hospital/doctor/view.html')

def PatientList(request):
    rec = patient.objects.all()
    return render(request, 'hospital/patient/view.html', {'rec': rec})

def PatientModal(request):
    data = patient.objects.get(id=request.GET['modalid'])
    rec={}
    rec['id'] = data.id
    rec['name']=data.name
    rec['address']=data.address
    rec['phone'] = data.phone
    rec['blood_group'] = data.blood_group
    rec['enroll'] = data.enroll
    return JsonResponse(rec)

def PatientEdit(request):
    rec = patient.objects.get(id=request.POST['patid'])
    if request.method == 'POST' :
     rec.name = request.POST['name']
     rec.address = request.POST['address']
     rec.blood_group = request.POST['blood_group']
     rec.phone = request.POST['phone']
     rec.enroll = request.POST['enroll']
     rec.save()
     return render(request, 'hospital/patient/view.html')

def PatientDelete(request):
    rec = patient.objects.get(id=request.GET['deleteid'])
    rec.delete()
    return render(request, 'hospital/patient/view.html')

def AppointmentList(request):
    rec = visit.objects.all()
    return render(request, 'hospital/appointment/view.html', {'rec': rec})

def AppointmentModal(request):
    data = visit.objects.get(id=request.GET['modalid'])
    rec={}
    rec['id'] = data.id
    rec['enroll'] = data.enroll
    rec['emp']= data.emp
    rec['category']= data.category
    rec['time'] = data.time
    rec['date'] = data.date
    return JsonResponse(rec)

def AppointmentEdit(request):
    rec = visit.objects.get(id=request.POST['appid'])
    if request.method == 'POST' :
     rec.enroll = request.POST['enroll']
     rec.emp = request.POST['emp']
     rec.category = request.POST['category']
     rec.time = request.POST['time']
     rec.date = request.POST['date']
     rec.save()
     return render(request, 'hospital/appointment/view.html')

def AppointmentDelete(request):
    rec = visit.objects.get(id=request.GET['deleteid'])
    rec.delete()
    return render(request, 'hospital/appointment/view.html')

templates/hospital/appointment/view.html
{% load static %}
<link rel="stylesheet" href="{% static 'hospital/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'hospital/dist/css/AdminLTE.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'hospital/style.css' %}">

            <h1>General Hospital</h1>
<header class="main-header">
    <nav class="navbar navbar-static-top">
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'hospital:index' %}">Home Page</a></li>
              <li><a href="{% url 'hospital:doctor' %}">Doctor Registraion</a></li>
              <li><a href="{% url 'hospital:patient' %}">Patient Registraion</a></li>
              <li><a href="{% url 'hospital:appoint' %}">Appointment Form</a></li>
              <li><a href="{% url 'hospital:doclist' %}">Doctors List</a></li>
              <li><a href="{% url 'hospital:patlist' %}">Patients List</a></li>
              <li><a href="{% url 'hospital:appointlist' %}">Appointment Record</a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="wrapper">
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <ul class="sidebar-menu" data-widget="tree">
              <li class="treeview">
               <a href="{% url 'hospital:index' %}">
               <i class="fa fa-files-o"></i>
               <span>Home</span>
               </a>
              </li>
              <li class="treeview">
               <a href="{% url 'hospital:doctor' %}">
               <i class="fa fa-files-o"></i>
               <span>Doctor Registration</span>
               </a>
              </li>
              <li class="treeview">
          <a href="{% url 'hospital:patient' %}">
          <i class="fa fa-files-o"></i>
          <span>Patient Registration</span>
              </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:appoint' %}">
                <i class="fa fa-files-o"></i>
        <span>Appointment Form</span>
             </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:doclist' %}">
          <i class="fa fa-files-o"></i>
          <span>Doctors List</span>
               </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:patlist' %}">
          <i class="fa fa-files-o"></i>
          <span>Patients List</span>
           </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:appointlist' %}">
          <i class="fa fa-files-o"></i>
          <span>Appointment Record</span>
               </a>
</li>
            </ul>
            </div>
    </section>
     </aside>
  <section class="content">
  <div class="row">
                <div class="col-md-10">
                <div style="margin-left:200px;padding:10px" class="box box-primary">
                <div class="box-header with-border">
              <h1 class="box-title">Appointment Record</h1>
            </div>
             <table id="app" class="table table-striped">
        <thead>
          <tr>
            <th>Visit ID</th>
            <th>Patient ID</th>
            <th>Doctor ID</th>
            <th>Category</th>
            <th>Time</th>
            <th>Date</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          {%for ap in rec %}
          <tr>
              <td>{{ap.id}}</td>
              <td>{{ap.enroll}}</td>
              <td>{{ap.emp}}</td>
              <td>{{ap.category}}</td>
              <td>{{ap.time}}</td>
              <td>{{ap.date}}</td>
              <td><button class="btn btn-danger" onclick="ModalShow(event)" data-id="{{ ap.id }}">Edit</button></td>
              <td><button class="btn btn-danger" onclick="del(event)" data-id="{{ ap.id }}">Delete</button></td>
           </tr>
        {% endfor %}
        </table>
                </div></div></div>
  <section class="content">
      <div id="appointmodal" class="modal">
        <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" id="closeModal" class-dismiss="modal">&times</button>
            <h3 class="modal-title">Enter New Values</h3> 
          </div>
          <div class="modal-body">
             <div class="form-group">
             <form role="form" action="{% url 'hospital:appointedit' %}" method="POST">
                {% csrf_token %}
               <input type="hidden" name="appid" id="appid">
               <label for="pat">Patient ID</label>
               <input type="text" class="form-control" id="pat" name="enroll">
               <label for="doc">Doctor ID</label>
               <input type="text" class="form-control" id="doc" name="emp">
               <label for="cat">Category</label>
               <input type="text" class="form-control" id="cat" name="category">
               <label for="tim">Time</label>
               <input type="text" class="form-control" id="tim" name="time">
               <label for="dat">Date</label>
               <input type="text" class="form-control" id="dat" name="date">
               <button type="submit" name="submit">Save</button>
            </form>
          </div>
          </div>
          <div class="model-footer">
            <button type="button" data-dismiss="modal">close</button>
          </div>
        </div></div></div>
                </section>
      </div>
 <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>H-12</b>
    </div>
    <strong><a href="{% url 'hospital:index' %}">Islamabad Clinic</a>.</strong>
  </footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
      function del(event){
        deleteid = $(event.target).data("id")
      $.ajax({
            url: "{% url 'hospital:appointdel' %}",
            data: {"deleteid":deleteid},
            success: function(resp) {
            document.location.reload(true);
    } }); };
       function ModalShow(event){
        $('#appointmodal').modal('show');
        modalid = $(event.target).data("id")
        $.ajax({
            url: "{% url 'hospital:appointmodal' %}",
            datatype: "json",
            data: {"modalid":modalid},
            success: function(rec){
                $('#appid').val(rec.id)
                $('#pat').val(rec.enroll)
                $('#doc').val(rec.emp)
                $('#cat').val(rec.category)
                $('#tim').val(rec.time)
                $('#dat').val(rec.date)
    } }); }
</script>

templates/hospital/doctor/view.html
{% load static %}
<link rel="stylesheet" href="{% static 'hospital/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'hospital/dist/css/AdminLTE.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'hospital/style.css' %}">


            <h1>General Hospital</h1>
<header class="main-header">
    <nav class="navbar navbar-static-top">
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'hospital:index' %}">Home Page</a></li>
              <li><a href="{% url 'hospital:doctor' %}">Doctor Registraion</a></li>
              <li><a href="{% url 'hospital:patient' %}">Patient Registraion</a></li>
              <li><a href="{% url 'hospital:appoint' %}">Appointment Form</a></li>
              <li><a href="{% url 'hospital:doclist' %}">Doctors List</a></li>
              <li><a href="{% url 'hospital:patlist' %}">Patients List</a></li>
              <li><a href="{% url 'hospital:appointlist' %}">Appointment Record</a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="wrapper">
    <aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <ul class="sidebar-menu" data-widget="tree">
              <li class="treeview">
               <a href="{% url 'hospital:index' %}">
               <i class="fa fa-files-o"></i>
               <span>Home</span>
               </a>
              </li>
                <li class="treeview">
                <a href="{% url 'hospital:doctor' %}">
                <i class="fa fa-files-o"></i>
                <span>Doctor Registration</span>
               </a>
              </li>
              <li class="treeview">
                <a href="{% url 'hospital:patient' %}">
                <i class="fa fa-files-o"></i>
                <span>Patient Registration</span>
              </a>
</li>
          <li class="treeview">
        <a href="{% url 'hospital:appoint' %}">
        <i class="fa fa-files-o"></i>
        <span>Appointment Form</span>
             </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:doclist' %}">
          <i class="fa fa-files-o"></i>
          <span>Doctors List</span>
               </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:patlist' %}">
          <i class="fa fa-files-o"></i>
          <span>Patients List</span>
           </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:appointlist' %}">
          <i class="fa fa-files-o"></i>
          <span>Appointment Record</span>
               </a>
</li>
            </ul>
            </div>
    </section>
     </aside>
        <div class="row">
                <div class="col-md-10">
                <div style="margin-left:200px;padding:10px" class="box box-primary">
                <div class="box-header with-border">
              <h1 class="box-title">Doctors List</h1>
            </div>
              <table id="tb" class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>Specialization</th>
                    <th>Phone</th>
                    <th>Emp No</th>
                    <th>Edit</td>
                    <th>Delete</td>
                </tr>
                {% for doctor in rec %}
                    <tr>
                    <td>{{doctor.id}}</td>
                    <td>{{doctor.name}}</td>
                    <td>{{doctor.address}}</td>
                    <td>{{doctor.specialize}}</td>
                    <td>{{doctor.phone}}</td>
                    <td>{{doctor.emp}}</td>
                    <td><button class="btn btn-danger" onclick="ModalShow(event)" data-id="{{ doctor.id }}">Edit</button></td>
                    <td><button class="btn btn-danger" onclick="del(event)" data-id="{{ doctor.id }}">delete</button></td>
                </tr>
                {% endfor %}
                </table>
                </div></div></div>
        <section class="content">
        <div id="docmodal" class="modal">
        <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" id="closeModal" class-dismiss="modal">&times</button>
            <h3 class="modal-title">Enter New Values</h3>
          </div>
          <div class="modal-body">
              <div class="form-group">
            <form role="form" action="{% url 'hospital:docedit' %}" method="POST">
               {% csrf_token %}
               <input type="hidden" name="docid" id="docid">
               <label for="nam">Name</label>
               <input type="text" class="form-control" id="nam" name="name">
               <label for="add">Address</label>
               <input type="text" class="form-control" id="add" name="address">
               <label for="ph">Phone</label>
               <input type="text" class="form-control" id="ph" name="phone">
               <label for="spec">Specialization</label>
               <input type="text" class="form-control" id="spec" name="specialize">
               <label for="emp">Emp No</label>
               <input type="text" class="form-control" id="emp" name="emp">
               <button type="submit" name="submit">Save</button>
            </form>
              </div>
              </div>
          <div class="model-footer">
            <button type="button" data-dismiss="modal">close</button>
          </div>
        </div></div></div>
        </section>
              </div>
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>H-12</b>
    </div>
         <strong><a href="{% url 'hospital:index' %}">Islamabad Clinic</a>.</strong>
  </footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
      function del(event){
        deleteid = $(event.target).data("id")
      $.ajax({
            url: "{% url 'hospital:docdel' %}",
            data: {"deleteid":deleteid},
            success: function(resp){
            document.location.reload(true);
    } }); }
      function ModalShow(event){
        $('#docmodal').modal('show');
        modalid = $(event.target).data("id")
        $.ajax({
            url: "{% url 'hospital:docmodal' %}",
            datatype: "json",
            data: {"modalid":modalid},
            success: function(rec){
                $('#docid').val(rec.id)
                $('#nam').val(rec.name)
                $('#add').val(rec.address)
                $('#ph').val(rec.phone)
                $('#spec').val(rec.specialize)
                $('#emp').val(rec.emp)

    } }); }
</script>

templates/hospital/patient/view.html
{% load static %}
<link rel="stylesheet" href="{% static 'hospital/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'hospital/dist/css/AdminLTE.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'hospital/style.css' %}">

    <h1>General Hospital</h1>
<header class="main-header">
    <nav class="navbar navbar-static-top">
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'hospital:index' %}">Home Page</a></li>
              <li><a href="{% url 'hospital:doctor' %}">Doctor Registraion</a></li>
              <li><a href="{% url 'hospital:patient' %}">Patient Registraion</a></li>
              <li><a href="{% url 'hospital:appoint' %}">Appointment Form</a></li>
              <li><a href="{% url 'hospital:doclist' %}">Doctors List</a></li>
              <li><a href="{% url 'hospital:patlist' %}">Patients List</a></li>
              <li><a href="{% url 'hospital:appointlist' %}">Appointment Record</a></li>
            </ul>
        </div>
    </nav>
</header>
<div class="wrapper">
<aside class="main-sidebar">
    <section class="sidebar">
        <div class="user-panel">
            <ul class="sidebar-menu" data-widget="tree">
              <li class="treeview">
                <a href="{% url 'hospital:index' %}">
               <i class="fa fa-files-o"></i>
               <span>Home</span>
               </a>
              </li>
              <li class="treeview">
              <a href="{% url 'hospital:doctor' %}">
               <i class="fa fa-files-o"></i>
               <span>Doctor Registration</span>
               </a>
              </li>
              <li class="treeview">
          <a href="{% url 'hospital:patient' %}">
          <i class="fa fa-files-o"></i>
          <span>Patient Registration</span>
              </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:appoint' %}">
                <i class="fa fa-files-o"></i>
        <span>Appointment Form</span>
             </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:doclist' %}">
          <i class="fa fa-files-o"></i>
          <span>Doctors List</span>
               </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:patlist' %}">
          <i class="fa fa-files-o"></i>
          <span>Patients List</span>
           </a>
</li>
          <li class="treeview">
          <a href="{% url 'hospital:appointlist' %}">
          <i class="fa fa-files-o"></i>
          <span>Appointment Record</span>
               </a>
</li>
            </ul>
            </div>
    </section>
     </aside>
      <section class="content">
      <div class="row">
      <div class="col-md-10">
      <div style="margin-left:200px;padding:10px" class="box box-primary">
      <div class="box-header with-border">
         <h1 class="box-title">Patients List</h1>
      </div>
      <table id="pat" class="table table-striped">
       <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Address</th>
            <th>Phone</th>
            <th>Blood Group</th>
            <th>Patient No</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          {% for patient in rec %}
        <tr>
            <td>{{patient.id}}</td>
            <td>{{patient.name}}</td>
            <td>{{patient.address}}</td>
            <td>{{patient.phone}}</td>
            <td>{{patient.blood_group}}</td>
            <td>{{patient.enroll}}</td>
            <td><button class="btn btn-danger" onclick="ModalShow(event)" data-id="{{ patient.id }}">Edit</button></td>
            <td><button class="btn btn-danger" onclick="del(event)" data-id="{{ patient.id }}">delete</button></td>
        </tr>
        {% endfor %}
        </table>
                </div></div></div>
        <section class="content">
        <div id="patmodal" class="modal">
        <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" id="closeModal" class-dismiss="modal">&times</button>
            <h3 class="modal-title">Enter New Values</h3> 
          </div>
          <div class="modal-body">
              <div class="form-group">
             <form role="form" action="{% url 'hospital:patedit' %}" method="POST">
                {% csrf_token %}
               <input type="hidden" name="patid" id="patid">
               <label for="nam">Name</label>
               <input type="text" class="form-control" id="nam" name="name">
               <label for="add">Address</label>
               <input type="text" class="form-control" id="add" name="address">
               <label for="ph">Phone</label>
               <input type="text" class="form-control" id="ph" name="phone">
               <label for="blood">Blood Group</label>
               <input type="text" class="form-control" id="blood" name="blood_group">
               <label for="enroll">Patient No</label>
               <input type="text" class="form-control" id="enroll" name="enroll">
               <button type="submit" name="submit">Save</button>
            </form>
          </div>
          </div>
            <div class="model-footer">
            <button type="button" data-dismiss="modal">close</button>
            </div>
        </div></div></div>
        </section>
        </div>
 <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>H-12</b>
    </div>
    <strong><a href="{% url 'hospital:index' %}">Islamabad Clinic</a>.</strong>
  </footer>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script>
    function del(event){
    deleteid = $(event.target).data("id")
    $.ajax({
            url: "{% url 'hospital:patdel' %}",
            data: {"deleteid":deleteid},
            success: function(resp) {
            document.location.reload(true);
    } }); };
    function ModalShow(event){
        $('#patmodal').modal('show');
        modalid = $(event.target).data("id")
        $.ajax({
            url: "{% url 'hospital:patmodal' %}",
            datatype: "json",
            data: {"modalid":modalid},
            success: function(rec){
                $('#patid').val(rec.id)
                $('#nam').val(rec.name)
                $('#add').val(rec.address)
                $('#ph').val(rec.phone)
                $('#blood').val(rec.blood_group)
                $('#enroll').val(rec.enroll)
    } }); }
</script>